matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      dist: trusty
      python: "2.7"
env:
  - ANSIBLE_VERSION="2.3.2.0"
install:
  - pip install ansible=="$ANSIBLE_VERSION"
before_script:
  - ansible --version
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
