os:
  - osx
  - linux
dist: trusty
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION="2.3.2.0"
install:
  - pip install ansible=="$ANSIBLE_VERSION"
before_script:
  - ansible --version
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
